# Dockerfile for the Client

# Base image
FROM node:20-alpine

# Working directory
WORKDIR /app

# Copy package.json
COPY package*.json .

# Install the dependencies
RUN npm install

# Copy files
COPY . .

# Expose the port
EXPOSE 3000

CMD [ "npm", "start" ]