# Dockerfile for the Node Server

# Base image
FROM node:20-alpine

# Working directory
WORKDIR /app

# Install nodemon
RUN npm install -g nodemon

# Copy files
COPY . .

# Install the dependencies
RUN npm install

# Expose the port
EXPOSE 5000

# Start the server
CMD [ "npm", "start" ]
